name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install compiler
      run: sudo apt-get update && sudo apt-get install -y g++
      
    - name: compile and run
      run: g++ -std=c++20 main.cpp sqlite3.o -o main
